server:
  port: 8081
spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://192.168.20.130:3306/hmall?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.20.130:8848
  rabbitmq:
    host: 192.168.20.130
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
mybatis-plus:
  type-aliases-package: com.hmall.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    cn.itcast.feign.client: debug
  pattern:
    dateformat: HH:mm:ss:SSS