server:
  port: 8084
spring:
  application:
    name: searchservice
  cloud:
    nacos:
      server-addr: 192.168.200.130:8848
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
logging:
  level:
    cn.itcast.feign.client: debug
  pattern:
    dateformat: HH:mm:ss:SSS
elasticsearch:
  host: 192.168.200.130
  port: 9200