server:
  port: 8083
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://192.168.200.130:3306/hmall?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.200.130:8848
mybatis-plus:
  type-aliases-package: com.hmall.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    cn.itcast.feign.client: debug
  pattern:
    dateformat: HH:mm:ss:SSS
xxljob:
  admin-address: http://192.168.200.130:8888/xxl-job-admin
  executor-name: hmall-order-executor
  executor-port: 9991
  log-path: C:/xxljob/logs
  # executor-address: http://192.168.200.1:9991